try to fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,41 +50,41 @@ jobs:
         run: |
           gcloud --quiet auth configure-docker $GCP_REGION-docker.pkg.dev
 
-      - name: Run file download script
-        run: python download.py
+      # - name: Run file download script
+      #   run: python download.py
 
       - name: Build and push Docker image
         run: |
           docker build -t $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/ulascan/$APP_NAME:latest .
           docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/ulascan/$APP_NAME:latest
 
-  deploy:
-    needs: build
-    runs-on: ubuntu-latest
+  # deploy:
+  #   needs: build
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Install SSH client
-        run: sudo apt-get install -y ssh
+  #   steps:
+  #     - name: Install SSH client
+  #       run: sudo apt-get install -y ssh
 
-      - name: Set up SSH
-        run: |
-          echo "$SSH_PRIVATE_KEY" > ssh_key
-          chmod 600 ssh_key
+  #     - name: Set up SSH
+  #       run: |
+  #         echo "$SSH_PRIVATE_KEY" > ssh_key
+  #         chmod 600 ssh_key
 
-      - name: Deploy to GCE
-        run: |
-          ssh -o StrictHostKeyChecking=no \
-            -i ssh_key \
-            ulascan@$GCE_INSTANCE_IP \
-            "gcloud --quiet auth configure-docker $GCP_REGION-docker.pkg.dev \
-            && docker pull $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/ulascan/$APP_NAME:latest \
-            && docker stop $APP_NAME || true \
-            && docker rm --force $APP_NAME || true \
-            && docker run -d \
-                --name $APP_NAME \
-                -p 5000:5000 \
-                $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/ulascan/$APP_NAME:latest \
-            && docker image prune -f"
+  #     - name: Deploy to GCE
+  #       run: |
+  #         ssh -o StrictHostKeyChecking=no \
+  #           -i ssh_key \
+  #           ulascan@$GCE_INSTANCE_IP \
+  #           "gcloud --quiet auth configure-docker $GCP_REGION-docker.pkg.dev \
+  #           && docker pull $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/ulascan/$APP_NAME:latest \
+  #           && docker stop $APP_NAME || true \
+  #           && docker rm --force $APP_NAME || true \
+  #           && docker run -d \
+  #               --name $APP_NAME \
+  #               -p 5000:5000 \
+  #               $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/ulascan/$APP_NAME:latest \
+  #           && docker image prune -f"
 
-      - name: Cleanup SSH key
-        run: rm ssh_key
+  #     - name: Cleanup SSH key
+  #       run: rm ssh_key
